config/routes.rb
Rails.application.routes.draw do
  resources :types

  resources :items do
    collection do
      get 'search'
    end
  end

 

end

app/models/item.rb
class Item < ActiveRecord::Base
    #def self.search(search)
        #if search
        #search_condition = "%" + search + "%"
        #find(:all, :conditions => ['title LIKE ? OR description LIKE?', search_condition, search_condition])
        #else
            #self.all
        #end
    #end


    belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # below written by wz
  def search
    if params[:opt_id]
      @results = result
    end
  end
  # up written by wz

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end


  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :type)
    end

    def result
      title = "%#{params[:title]}%"
      description = "%#{params[:description]}%"
      owner = "%#{params[:owner]}%"
      type_id = params[:item][:type_id]
      if params[:opt_id] == '1'
        Item.where("title LIKE ? OR description LIKE ? OR owner LIKE ? OR type_id = #{type_id}", title, description, owner)
      elsif params[:opt_id] == '2'
        Item.where("title LIKE ? AND description LIKE ? AND owner LIKE ? AND type_id = #{type_id}", title, description, owner)
      end
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
<div class="form-group">
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
 
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :owner %><br>
    <%= f.text_area :owner, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :type %><br>
    
    <select name="type_id" id="type_id" class="form-control">
      <option value="1">book</option>
      <option value="2">clothing</option>
      <option value="3">cellphone</option>
      <option value="4">computer</option>
    </select>
    
  </div>
  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Type_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.owner %></td>
        <td><%= item.type_id %></td>
       

        <td><%= link_to 'Show', item, :class => 'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_item_path(item), :class => 'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-xs btn-default'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path , :class => 'btn btn-sm btn-default'%><br><br>
<%= link_to 'Search', search_items_path , :class => 'btn btn-sm btn-default' %>

</div>

app/views/items/new.html.erb
<div class="container">
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>
</div>

app/views/items/search.html.erb
<h2>Search Conditions</h2>
<%= form_tag(search_items_path, method: "get") do %>
   
  <br>
  <%= label_tag(:q, "Search for:") %>
  <%= select_tag(:opt_id, options_for_select([['All of these conditions(AND)', 2], ['Any of these conditions(OR)', 1]])) %>
  <br>

  <%= label_tag(:q, "Title:") %>
  <%= text_field_tag(:title) %>
  <br>

  <%= label_tag(:q, "Description:") %>
  <%= text_field_tag(:description) %>
  <br>

  <%= label_tag(:q, "Owner:") %>
  <%= text_field_tag(:owner) %>
  <br>

  <%= label_tag(:q, "Type:") %>
  <%= collection_select(:item, :type_id, Type.all, :id, :title) %>
  <br>
  <br>
  <%= submit_tag("Search") %>
<% end %>

<% if @results %>
  <h2>Search Results</h2>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.owner %></td>
        <td><%= item.type.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @item.owner %>
</p>

<p>
  <strong>Type_id:</strong>
  <%= @item.type_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostandfound</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

<%= yield %>



</body>
</html>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.title %></td>
        <td><%= type.description %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @type.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @type.description %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>